Make new GameState class, minor refactor
Tequila-Mockingbird-Chevaliers/pygameSummerJam pull request #2
Opened 2021-07-26 14:01 UTC by ankith26

2021-07-26 20:42 UTC, Grimmys requested changes

2021-07-26 20:42 UTC, Grimmys commented on src/entities/ball.py
> +        Initialise Ball class
typo: initialize I'm right?

2021-07-26 20:42 UTC, Grimmys commented on src/entities/game_object.py
> +        if self.image is not None and self.rect is not None:
Do we really need `is not None` instead of `if self.image and self.rect:`?
I'm curious to learn new things.

2021-07-26 20:42 UTC, Grimmys commented on src/entities/laser.py
> +    def __init__(self, game_state: GameState, spaceship: Spaceship):
I'm worried by the fact we don't call the parent init method anymore for this object and all others in fact... I fear that we are breaking a key point of OOP lol, and moreover we have duplicate code (for example `self.game_state = game_state` is literally the same statement than in parent init method).
Maybe I can try something to fix that.

2021-07-26 20:42 UTC, Grimmys commented on src/entities/paddle.py
> +        self.game_state = game_state
More I compare the init implementation of each object (Paddle, Ball, Laser etc.) more I find them really similar, I'm sure we can do better hehe.

2021-07-26 20:42 UTC, Grimmys commented on src/entities/game_object.py
> +        self.game_state = game_state
Should game objects really be aware of the game state and store it as an attribute?
It seems weird to me, the game scene should definitely have a reference to the game state and should handling its evolution, but the game objects should not have a control other it, if they need to know the score (for example), the scene can provide them the current value as an argument to a specific method.
It's only my pov.

2021-07-27 02:51 UTC, ankith26 commented on src/entities/ball.py
> +        Initialise Ball class
Ohh well I guess it is another american-british english thing. But yea "initialize" is more common, so I guess we should switch to it

2021-07-27 02:57 UTC, ankith26 commented on src/entities/game_object.py
> +        if self.image is not None and self.rect is not None:
Yea, `if self.rect` just truth-tests the variable. This means that it is `False` if `None`, and if it is a `Rect` object, it uses the `__bool__` method to determine the truth value of the object. Clearly, we want to test for an explicit `None` here, and not the truth value

2021-07-27 02:59 UTC, ankith26 commented on src/entities/laser.py
> +    def __init__(self, game_state: GameState, spaceship: Spaceship):
Yea right, but I made it this way so that the subclass init does everything the parent init is doing anyways, so the super init call would be redundant. But maybe you are right, for more clarity sake, I should be calling super init

2021-07-27 03:01 UTC, ankith26 commented on src/entities/game_object.py
> +        self.game_state = game_state
Yea, I am not particularly happy with this system too. But in cases when a game object needs to spawn a new object, or maybe increase the score, it needs access to the game state

2021-07-27 09:09 UTC, Grimmys commented on src/entities/ball.py
> +        Initialise Ball class
Oh no no no, if the word exists in some English local variation it's ok!
Sorry lol

2021-07-27 09:13 UTC, Grimmys commented on src/entities/laser.py
> +    def __init__(self, game_state: GameState, spaceship: Spaceship):
Well, no, it doesn't have to be redundant.
In fact, it is the call to the super init that avoids to have redundancy in each object initialization!
You can check what I pushed, maybe we can even remove the `rect` argument because we don't use it... I found it weird at first glance, I'm always used to simply pass the `image` as an argument and compute the `rect` according to the `image`.

2021-07-27 09:15 UTC, Grimmys commented on src/entities/game_object.py
> +        self.game_state = game_state
Okay, I still find it weird (for example, if we want to increase the score after the ball hits a brick... In which world would it be ball duty (or brick duty??) to do it, lol), but I understand your point. It's a detail, maybe it's simpler to do it that way. =)

2021-07-27 09:15 UTC, ankith26 commented on src/entities/ball.py
> +        Initialise Ball class
No worries lol

2021-07-27 09:25 UTC, ankith26 commented on src/entities/laser.py
> +    def __init__(self, game_state: GameState, spaceship: Spaceship):
Yea, your new commit fixes things up pretty well, nice!

2021-07-27 14:00 UTC, Grimmys approved these changes

2021-07-27 14:00 UTC, merged